# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopcarts-ingress
  annotations:
    # kubernetes.io/ingress.class: "nginx"
spec:
  # k3d/k3s default Traefikï¼›if NGINX Ingress then "nginx"
  ingressClassName: traefik
  rules:
  - host: shopcarts.local
    http:
      paths:
      - path: /shopcarts
        pathType: Prefix
        backend:
          service:
            name: shopcarts
            port:
              number: 8080
