apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: shopcarts
  labels:
    app: shopcarts
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: shopcarts
    weight: 100
  wildcardPolicy: None

