apiVersion: v1
kind: Service
metadata:
  name: shopcarts
  labels:
    app: shopcarts
spec:
  type: ClusterIP
  selector:
    app: shopcarts
  ports:
    - name: http
      port: 8080
      targetPort: 8080
